In [1]:
#import libraries
import numpy as np
from matplotlib import pyplot as plt

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
#define constants
n = 5
d = 3

#define data mean & prior mean
real_mean = -1 * np.ones(d)
prior_mean = np.zeros(d)

#define data & prior covariance
real_cov = np.array([[1,0,-0.2],[0,0.8,0.3],[-0.2,0.3,1.1]])
prior_cov = np.identity(d)

#sample observations
obs = np.random.multivariate_normal(real_mean, real_cov, n).T


In [4]:
#compute batch bayesian estimates of the posterior mean and covariance
post_mean = prior_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ np.average(obs,1) + real_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ prior_mean / n 
post_cov = prior_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ real_cov / n

In [5]:
def p_estimator(observation, p0_mean, p0_cov, r_cov):
    n = 1
    mean = p0_cov @ np.linalg.inv(p0_cov + r_cov / n) @ observation + r_cov @ np.linalg.inv(p0_cov + r_cov / n) @ p0_mean / n 
    cov = p0_cov @ np.linalg.inv(p0_cov + r_cov / n) @ r_cov / n
    return mean, cov

In [6]:
p_mean = prior_mean
p_cov = prior_cov
#obs2 = np.vstack([prior_mean, obs.T]).T
for i in range(n):
    observation = obs[:,i]
    p_mean, p_cov = p_estimator(observation, p_mean, p_cov, real_cov)

In [7]:
post_mean

array([-1.19313129, -1.61608733, -1.44370324])

In [11]:
p_mean

array([-1.19313129, -1.61608733, -1.44370324])

In [9]:
post_cov

array([[ 0.1657526 ,  0.00141839, -0.02742213],
       [ 0.00141839,  0.13573009,  0.04255158],
       [-0.02742213,  0.04255158,  0.17733608]])

In [12]:
p_cov

array([[ 0.1657526 ,  0.00141839, -0.02742213],
       [ 0.00141839,  0.13573009,  0.04255158],
       [-0.02742213,  0.04255158,  0.17733608]])