In [159]:
#import packages
import numpy as np
from matplotlib import pyplot as plt

In [160]:
#define constants
n = 100
d = 3

#define data mean & prior mean
real_mean = -1 * np.ones(d)
prior_mean = np.zeros(d)

#define data & prior covariance
real_cov = np.array([[1,0,-0.2],[0,0.8,0.3],[-0.2,0.3,1.1]])
prior_cov = np.identity(d)

#sample observations
obs = np.random.multivariate_normal(real_mean, real_cov, n).T


In [161]:
post_mean = prior_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ np.average(obs,1) + real_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ prior_mean / n 
post_cov = prior_cov @ np.linalg.inv(prior_cov + (real_cov / n)) @ real_cov / n

In [169]:
def p_estimator(observation, p0_mean, p0_cov, r_cov):
    mean = p0_cov @ np.linalg.inv(p0_cov + (pn_cov / n)) @ observation + real_cov @ np.linalg.inv(p0_cov + (pn_cov / n)) @ p0_mean / n 
    cov = p0_cov @ np.linalg.inv(p0_cov + (r_cov / n)) @ r_cov
    return mean, cov

In [170]:
p0_mean = prior_mean
p0_cov = prior_cov
for i in range(5):
    observation = obs[:,i]
    p0_mean, p0_cov = p_estimator(observation, p0_mean, p0_cov, real_cov)

In [171]:
post_mean

array([-0.95281816, -1.05084753, -0.96692201])

In [172]:
post_cov

array([[ 9.89711153e-03,  5.82939824e-06, -1.95867781e-03],
       [ 5.82939824e-06,  7.92774649e-03,  2.94384611e-03],
       [-1.95867781e-03,  2.94384611e-03,  1.08677063e-02]])

In [173]:
p0_mean

array([-2.13969496, -0.03269496, -1.00234951])

In [174]:
p0_cov

array([[ 9.90000000e-01,  5.88060434e-12, -1.98000000e-01],
       [ 5.88062099e-12,  7.92000000e-01,  2.97000000e-01],
       [-1.98000000e-01,  2.97000000e-01,  1.08900000e+00]])

In [168]:
real_cov

array([[ 1. ,  0. , -0.2],
       [ 0. ,  0.8,  0.3],
       [-0.2,  0.3,  1.1]])